### ISSUE TITLE
run lint: esw webpack.config

### ISSUE THREAD

**Issue by trickydisco78** [coryhouse/pluralsight-redux-starter#37]
Node version:6.9.1

npm version:3.10.8

Operating system:Win 10

Command line used:npm run lint
![image](https://cloud.githubusercontent.com/assets/3627429/20434259/eef8e706-ad9e-11e6-8f1b-43223d399d10.png)

Steps to reproduce:

I run the command npm run lint and get this issue with the esw script.

I've got esw.cmd and esw in /.bin folder but this script won't run

Why is it being run through esw rather than eslint?

**Comment by coryhouse** [comment]
esw is eslint-watch. It's a wrapper around eslint that adds watch capability.

Regarding your issue, if you have a .eslintrc in your user file, be sure to delete it. It's likely conflicting with the course's .eslintrc. 

If that doesn't work, please check this list: https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first

**Comment by trickydisco78** [comment]
i've fixed it. It was complaing about paths which i think is an issue with eslint-watch 2.1.11. I updated to 2.1.14 (both globally and locally) and it fixed it

**Comment by bensezio** [comment]
Hi @coryhouse,
I am currently struggling with the same issue. I have updated eslint-watch to 2.1.14 but issue still persists.

`npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "lint"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter@1.0.0 lint: `esw webpack.config.* src tools`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-starter@1.0.0 lint script 'esw webpack.config.* src tools'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     esw webpack.config.* src tools
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/benedictsefaziorklui/Documents/PROJECTS/WIPRO_REACT-BZ/npm-debug.log
ERROR: lint: None-Zero Exit(1);

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter@1.0.0 prebuild: `npm-run-all clean-dist test lint build:html`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-starter@1.0.0 prebuild script 'npm-run-all clean-dist test lint build:html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all clean-dist test lint build:html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter
`

**Comment by bensezio** [comment]
I have managed to fix this issue by following the instructions from Evilcat325 on this thread
https://github.com/coryhouse/react-slingshot/issues/151

**Comment by coryhouse** [comment]
The link you provided doesn't work, but based on the screenshot, it looks like you just need to run npm install. :)

**Comment by walifaizy** [comment]
Hi Cory npm modules are already install, i think their are some linting issues, below is my working project link
[https://github.com/walifaizy/react-redux-library.git](url)
Thanks

**Comment by coryhouse** [comment]
I just cloned that repo, ran npm install, then npm start and it started fine without any warnings.

**Comment by walifaizy** [comment]
i am also doing the same thing from the last night, but i am not able to
debug the console errors

**Comment by coryhouse** [comment]
Here's what I get. It looks like you just didn't run npm install. 

cory@Mac ~/Desktop/react-redux-library                                                                                                                                                              [7:44:31]
> $ npm run lint                                                                                                                                                                         

> course-library@1.0.0 lint /Users/cory/Desktop/react-redux-library
> esw webpack.config.* src tools

/Users/cory/Desktop/react-redux-library/src/index.js (0/1)
  !  1:1  Unexpected console statement  no-console

! 1 warning (7:44:36 AM)

**Comment by walifaizy** [comment]
I dont know what is happening, i have deleted node modules folder and run
npm install many times, i am moving towards the initial app structure ,
their is an same issue of unresolve path

C:\Users\Zenul\desktop\react-redux-bookstore\src\components\about\HomePage.js
(2/0)
  ✖  1:32  Unable to resolve path to module 'react'
import/no-unresolved
  ✖  2:20  Unable to resolve path to module 'react-router'
 import/no-unresolved

✖ 2 errors (4:47:18 PM)


C:\Users\Zenul\desktop\react-redux-bookstore\src\components\about\HomePage.js
(2/0)
  ✖  1:32  Unable to resolve path to module 'react'
import/no-unresolved
  ✖  2:20  Unable to resolve path to module 'react-router'
 import/no-unresolved

✖ 2 errors (4:47:18 PM)

**Comment by coryhouse** [comment]
Make sure you're running npm install in the same path as package.json. You should see node_modules populated with many folders after you do.

**Comment by walifaizy** [comment]
The package.json and node-modules are in same root folder, If I run npm
start without linting, than it is working properly but if I use with
lintion than it is giving same error below

C:\Users\Zenul\desktop\react-redux-bookstore\src\components\about\HomePage.js
(2/0)
  ✖  1:32  Unable to resolve path to module 'react'
import/no-unresolved
  ✖  2:20  Unable to resolve path to module 'react-router'
 import/no-unresolved

C:\Users\Zenul\desktop\react-redux-bookstore\src\components\home\AboutPage.js
(1/0)
  ✖  1:32  Unable to resolve path to module 'react'  import/no-unresolved

C:\Users\Zenul\desktop\react-redux-bookstore\src\index.js (0/1)
  !  1:1  Unexpected console statement  no-console

C:\Users\Zenul\desktop\react-redux-bookstore\tools\server.js (4/0)
  ✖  1:21  Unable to resolve path to module 'express'
 import/no-unresolved
  ✖  2:21  Unable to resolve path to module 'webpack'
 import/no-unresolved
  ✖  4:20  Unable to resolve path to module '../webpack.config.dev'
 import/no-unresolved
  ✖  5:18  Unable to resolve path to module 'open'
import/no-unresolved

C:\Users\Zenul\desktop\react-redux-bookstore\tools\startMessage.js (1/0)
  ✖  1:20  Unable to resolve path to module 'colors'  import/no-unresolved

✖ 9 errors ! 1 warning (5:42:32 PM)

**Comment by Bahaa-Addin** [comment]
`npm i -g eslint eslint-watch`
